
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raccoon
 */
public class bebida extends javax.swing.JFrame {

    /**
     * Creates new form bebida
     */
    public bebida() {
        initComponents();
        limpiar();
        llenarTabla();
        llenarComboBoxBebida();
        
        cbIdBebida.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBebida = new javax.swing.JTable();
        txtNombreBebida = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGuardarBebida = new javax.swing.JButton();
        cbBebida = new javax.swing.JComboBox<>();
        btnAgregarIngredientes = new javax.swing.JButton();
        cbIdBebida = new javax.swing.JComboBox<>();
        btnEliminarBebida = new javax.swing.JButton();
        btnActualizarBebida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnVolver.setText("<= Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tableBebida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ));
        tableBebida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBebidaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBebida);

        txtNombreBebida.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtNombreBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBebidaActionPerformed(evt);
            }
        });

        txtPrecio.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel1.setText("Nombre :");

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel2.setText("Precio :");

        btnGuardarBebida.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnGuardarBebida.setText("Guardar");
        btnGuardarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarBebidaActionPerformed(evt);
            }
        });

        cbBebida.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBebidaActionPerformed(evt);
            }
        });

        btnAgregarIngredientes.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnAgregarIngredientes.setText("Agregar");
        btnAgregarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarIngredientesActionPerformed(evt);
            }
        });

        cbIdBebida.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbIdBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdBebidaActionPerformed(evt);
            }
        });

        btnEliminarBebida.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnEliminarBebida.setText("Eliminar");
        btnEliminarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarBebidaActionPerformed(evt);
            }
        });

        btnActualizarBebida.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnActualizarBebida.setText("Actualizar");
        btnActualizarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarBebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVolver)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombreBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnActualizarBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminarBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuardarBebida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbIdBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardarBebida)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnEliminarBebida)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizarBebida)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarIngredientes)
                    .addComponent(cbIdBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        inicio_creacion inicio_creacion = new inicio_creacion();
        inicio_creacion.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tableBebidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBebidaMouseClicked
        int  fila = tableBebida.getSelectedRow();
        txtNombreBebida.setText((String) tableBebida.getValueAt(fila, 0));
        txtPrecio.setText((String) tableBebida.getValueAt(fila, 1));
    }//GEN-LAST:event_tableBebidaMouseClicked

    private void txtNombreBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBebidaActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnGuardarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarBebidaActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String nombre;
        int precio;

        nombre = txtNombreBebida.getText();
        precio = Integer.parseInt(txtPrecio.getText());

        try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO bebida VALUES (?,?,?)");
            pst.setString(2, nombre);
            pst.setInt(3, precio);
            pst.executeUpdate();
            limpiar();
            llenarTabla();
            llenarComboBoxBebida();
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnGuardarBebidaActionPerformed

    private void cbBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBebidaActionPerformed
        if(cbBebida.getSelectedIndex() > -1){
            cbIdBebida.setSelectedIndex(cbBebida.getSelectedIndex());
            //tableStock.removeAll();
            //String num = (String)cbIdSushi.getSelectedItem();
            //int id = Integer.parseInt(num);
            //llenarTableStock(id);
        }else{
            cbBebida.removeAll();
        }
    }//GEN-LAST:event_cbBebidaActionPerformed

    private void btnAgregarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIngredientesActionPerformed
        String id = (String)cbIdBebida.getSelectedItem();
        bebida_ingredientes bebida_ingredientes = new bebida_ingredientes(id);
        bebida_ingredientes.setLocationRelativeTo(null);
        bebida_ingredientes.setResizable(true);
        bebida_ingredientes.setVisible(true);
        dispose();

        /*Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String nombre, stock, sushi, numero;
        int id_stock, id_sushi, cantidad;
        nombre = (String)cbStock.getSelectedItem();
        stock = (String)cbIdStock.getSelectedItem();
        id_stock = Integer.parseInt(stock);
        sushi = (String)cbIdSushi.getSelectedItem();
        id_sushi = Integer.parseInt(sushi);
        cantidad = Integer.parseInt(txtCantidad.getText());

        try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO sushi_ingredientes VALUES (?,?,?,?,?)");
            pst.setInt(2, id_stock);
            pst.setInt(3, id_sushi);
            pst.setString(4, nombre);
            pst.setInt(5, cantidad);
            pst.executeUpdate();
            limpiar();
            llenarTableStock(id_sushi);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }*/
    }//GEN-LAST:event_btnAgregarIngredientesActionPerformed

    private void cbIdBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdBebidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdBebidaActionPerformed

    private void btnEliminarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarBebidaActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String nombre = txtNombreBebida.getText();

        try
        {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea ELIMINAR esta bebida?");

            if (confirmacion == 0){

                PreparedStatement pst = cn.prepareStatement("DELETE FROM bebida WHERE nombre = ?");
                pst.setString(1, nombre);
                pst.executeUpdate();
                limpiar();
                llenarTabla();
                llenarComboBoxBebida();
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarBebidaActionPerformed

    private void btnActualizarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarBebidaActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String nombre;
        int precio;

        nombre = txtNombreBebida.getText();
        precio = Integer.parseInt(txtPrecio.getText());

        try
        {
            PreparedStatement pst = cn.prepareStatement("UPDATE bebida SET precio = ? WHERE nombre = ?");
            pst.setInt(1, precio);
            pst.setString(2, nombre);
            pst.executeUpdate();
            limpiar();
            llenarTabla();
            llenarComboBoxBebida();
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnActualizarBebidaActionPerformed

    public void limpiar(){
    txtNombreBebida.setText("");
    txtPrecio.setText("");
    txtNombreBebida.requestFocus();
    }
    
    public void llenarTabla(){
        
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        
        String [] fila = new String[3];

        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet bebida = st.executeQuery("SELECT * FROM bebida");
                        
            while(bebida.next()){
                //System.out.println(stock.getString(2) + " " + stock.getString(3) + " " + stock.getString(4));
                //fila[1] = stock.getString(3) + " " + stock.getString(4);
                fila[0] = bebida.getString(2);
                fila[1] = bebida.getString(3);
                modelo.addRow(fila);
            }
            
            tableBebida.setModel(modelo);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }
    
    public void llenarComboBoxBebida(){
        
        cbBebida.removeAllItems();
        cbIdBebida.removeAllItems();
        DefaultComboBoxModel modeloSalsa = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloId = new DefaultComboBoxModel();
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet bebida = st.executeQuery("SELECT * FROM bebida");
            
            while(bebida.next()){
                modeloSalsa.addElement(bebida.getString(2));
                modeloId.addElement(bebida.getString(1));
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
        cbBebida.setModel(modeloSalsa);
        cbIdBebida.setModel(modeloId);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarBebida;
    private javax.swing.JButton btnAgregarIngredientes;
    private javax.swing.JButton btnEliminarBebida;
    private javax.swing.JButton btnGuardarBebida;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbBebida;
    public static javax.swing.JComboBox<String> cbIdBebida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBebida;
    private javax.swing.JTextField txtNombreBebida;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
