/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raccoon
 */
public class inicio_creacion extends javax.swing.JFrame {

    /**
     * Creates new form inicio_creacion
     */
    public inicio_creacion() {
        initComponents();
        CentrarJFrame();
    }
    
    public void CentrarJFrame(){
    setLocationRelativeTo(null);
    setResizable(false);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAcompañamiento = new javax.swing.JButton();
        btnSushi = new javax.swing.JButton();
        btnSalsa = new javax.swing.JButton();
        btnSashimi = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnPlatos = new javax.swing.JButton();
        btnMenu1 = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAcompañamiento.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnAcompañamiento.setText("Crear Acompañamientos");
        btnAcompañamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcompañamientoActionPerformed(evt);
            }
        });

        btnSushi.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnSushi.setText("Crear Rolls");
        btnSushi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSushiActionPerformed(evt);
            }
        });

        btnSalsa.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnSalsa.setText("Crear Salsas");
        btnSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalsaActionPerformed(evt);
            }
        });

        btnSashimi.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnSashimi.setText("Crear Sashimi y Tiraritos");
        btnSashimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSashimiActionPerformed(evt);
            }
        });

        btnMenu.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnMenu.setText("Crear Menus");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        btnPlatos.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnPlatos.setText("Crear Platos Frios y Calientes");
        btnPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlatosActionPerformed(evt);
            }
        });

        btnMenu1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        btnMenu1.setText("Crear Bebidas");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnVolver.setText("<=Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSashimi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPlatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAcompañamiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalsa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSushi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(27, 27, 27)
                .addComponent(btnSushi)
                .addGap(18, 18, 18)
                .addComponent(btnSalsa)
                .addGap(18, 18, 18)
                .addComponent(btnAcompañamiento)
                .addGap(18, 18, 18)
                .addComponent(btnPlatos)
                .addGap(18, 18, 18)
                .addComponent(btnSashimi)
                .addGap(18, 18, 18)
                .addComponent(btnMenu)
                .addGap(18, 18, 18)
                .addComponent(btnMenu1)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcompañamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcompañamientoActionPerformed
        acompañamiento acompañamiento = new acompañamiento();
        acompañamiento.setLocationRelativeTo(null);
        acompañamiento.setResizable(false);
        acompañamiento.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAcompañamientoActionPerformed

    private void btnSushiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSushiActionPerformed
        sushi sushi = new sushi();
        sushi.setLocationRelativeTo(null);
        sushi.setResizable(false);
        sushi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSushiActionPerformed

    private void btnSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalsaActionPerformed
        salsa salsa = new salsa();
        salsa.setLocationRelativeTo(null);
        salsa.setResizable(false);
        salsa.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalsaActionPerformed

    private void btnSashimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSashimiActionPerformed
        sashimi sashimi = new sashimi();
        sashimi.setLocationRelativeTo(null);
        sashimi.setResizable(false);
        sashimi.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSashimiActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        menu menu = new menu();
        menu.setLocationRelativeTo(null);
        menu.setResizable(false);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlatosActionPerformed
        plato plato = new plato();
        plato.setLocationRelativeTo(null);
        plato.setResizable(false);
        plato.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPlatosActionPerformed

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        bebida bebida = new bebida();
        bebida.setLocationRelativeTo(null);
        bebida.setResizable(false);
        bebida.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMenu1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        inicio inicio = new inicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio_creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio_creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio_creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio_creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio_creacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcompañamiento;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnMenu1;
    private javax.swing.JButton btnPlatos;
    private javax.swing.JButton btnSalsa;
    private javax.swing.JButton btnSashimi;
    private javax.swing.JButton btnSushi;
    private javax.swing.JButton btnVolver;
    // End of variables declaration//GEN-END:variables
}
