
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raccoon
 */
public class menu_plato extends javax.swing.JFrame {

    /**
     * Creates new form menu_plato
     */
    public menu_plato(String folio) {
        initComponents();
        txtFolio.setText(folio);
        int plato = Integer.parseInt(txtFolio.getText());
        llenarTablePlato(plato);
        String tipoPlato = (String)cbTipoPlato.getSelectedItem();
        llenarComboBoxPlato(tipoPlato);
        
        txtFolio.setVisible(false);
        cbIdPlato.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar2 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePlato = new javax.swing.JTable();
        cbIdPlato = new javax.swing.JComboBox<>();
        cbTipoPlato = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        cbPlato = new javax.swing.JComboBox<>();
        btnCerrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCerrar2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnCerrar2.setText("Eliminar");
        btnCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar2ActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        txtFolio.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N

        tablePlato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablePlato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ));
        tablePlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePlatoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePlato);

        cbIdPlato.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbIdPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdPlatoActionPerformed(evt);
            }
        });

        cbTipoPlato.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbTipoPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platos Calientes", "Platos Frios" }));
        cbTipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPlatoActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnVolver.setText("<=Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        cbPlato.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlatoActionPerformed(evt);
            }
        });

        btnCerrar1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnCerrar1.setText("Agregar");
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(cbTipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(cbPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbIdPlato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(btnCerrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar1)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbIdPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar2ActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        int id = Integer.parseInt(txtFolio.getText());
        String nombre = txtNombre.getText();

        try
        {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea ELIMINAR este plato?");

            if (confirmacion == 0){

                PreparedStatement pst = cn.prepareStatement("DELETE FROM menu_plato WHERE ( nombre = ? AND id_menu = ? )");
                pst.setString(1, nombre);
                pst.setInt(2, id);
                pst.executeUpdate();

                limpiar();
                llenarTablePlato(id);
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnCerrar2ActionPerformed

    private void tablePlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePlatoMouseClicked
        int  fila = tablePlato.getSelectedRow();
        txtNombre.setText((String) tablePlato.getValueAt(fila, 1));
    }//GEN-LAST:event_tablePlatoMouseClicked

    private void cbIdPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdPlatoActionPerformed

    private void cbTipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPlatoActionPerformed
        if(cbTipoPlato.getSelectedIndex() > -1){
            String tipoPlato = (String)cbTipoPlato.getSelectedItem();
            llenarComboBoxPlato(tipoPlato);
        }else{
            cbTipoPlato.removeAll();
        }
    }//GEN-LAST:event_cbTipoPlatoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        menu menu = new menu();
        menu.setLocationRelativeTo(null);
        menu.setResizable(false);
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlatoActionPerformed
        if(cbPlato.getSelectedIndex() > -1){
            cbIdPlato.setSelectedIndex(cbPlato.getSelectedIndex());
        }else{
            cbPlato.removeAll();
        }
    }//GEN-LAST:event_cbPlatoActionPerformed

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String nombre, idplato, precioplato, tipo;
        int id_venta, id_plato, id;

        nombre = (String)cbPlato.getSelectedItem();
        id_venta = Integer.parseInt(txtFolio.getText());
        idplato = (String)cbIdPlato.getSelectedItem();
        id_plato = Integer.parseInt(idplato);
        id = Integer.parseInt(txtFolio.getText());
        tipo = (String)cbTipoPlato.getSelectedItem();

        try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO menu_plato VALUES (?,?,?,?,?)");
            pst.setInt(2, id_venta);
            pst.setInt(3, id_plato);
            pst.setString(4, tipo);
            pst.setString(5, nombre);
            pst.executeUpdate();

            llenarTablePlato(id_venta);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    public void llenarTablePlato(int folio){
        
        DefaultTableModel stock = new DefaultTableModel();
        
        stock.addColumn("Tipo");
        stock.addColumn("Nombre");
        
        String [] fila = new String[5];

        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet plato = st.executeQuery("SELECT * FROM menu_plato WHERE id_menu =" + folio);
                        
            while(plato.next()){
                
                fila[0] = plato.getString(4);
                //fila[1] = stock.getString(3) + " " + stock.getString(4);
                fila[1] = plato.getString(5);

                stock.addRow(fila);
            }
            
            tablePlato.setModel(stock);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }
    
    public void llenarComboBoxPlato(String tipo){
        
        cbPlato.removeAllItems();
        cbIdPlato.removeAllItems();
        DefaultComboBoxModel modeloPlato = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloId = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloPrecio = new DefaultComboBoxModel();
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            System.out.println(tipo);
            Statement st = cn.createStatement();
            ResultSet plato = st.executeQuery("SELECT * FROM plato WHERE tipo = '" + tipo + "'");
            
            while(plato.next()){
                modeloPlato.addElement(plato.getString(2));
                modeloId.addElement(plato.getString(1));
                modeloPrecio.addElement(plato.getString(4));
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
        cbPlato.setModel(modeloPlato);
        cbIdPlato.setModel(modeloId);
}
    
    public void limpiar(){
    txtNombre.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnCerrar2;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbIdPlato;
    private javax.swing.JComboBox<String> cbPlato;
    private javax.swing.JComboBox<String> cbTipoPlato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePlato;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
