
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raccoon
 */
public class menu_sushi extends javax.swing.JFrame {

    /**
     * Creates new form menu_sushi
     */
    public menu_sushi(String folio) {
        initComponents();
        txtFolio.setText(folio);
        int sushi = Integer.parseInt(txtFolio.getText());
        llenarTableSushi(sushi);
        String tipoSushi = (String)cbTipoSushi.getSelectedItem();
        llenarComboBoxSushi(tipoSushi);
        
        txtFolio.setVisible(false);
        cbIdSushi.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFolio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSushi = new javax.swing.JTable();
        cbIdSushi = new javax.swing.JComboBox<>();
        cbTipoSushi = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        cbSushi = new javax.swing.JComboBox<>();
        btnCerrar1 = new javax.swing.JButton();
        btnCerrar2 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtFolio.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N

        tableSushi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableSushi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ));
        tableSushi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSushiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSushi);

        cbIdSushi.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        cbIdSushi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdSushiActionPerformed(evt);
            }
        });

        cbTipoSushi.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbTipoSushi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Especial Rolls", "Veggie Rolls", "Hot Rolls", "Rolls sin Arroz" }));
        cbTipoSushi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoSushiActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnVolver.setText("<=Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        cbSushi.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbSushi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSushiActionPerformed(evt);
            }
        });

        btnCerrar1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnCerrar1.setText("Agregar");
        btnCerrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar1ActionPerformed(evt);
            }
        });

        btnCerrar2.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnCerrar2.setText("Eliminar");
        btnCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar2ActionPerformed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(cbTipoSushi, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(cbSushi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbIdSushi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCerrar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre)
                            .addComponent(btnCerrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar1)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoSushi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSushi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCerrar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbIdSushi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableSushiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSushiMouseClicked
        int  fila = tableSushi.getSelectedRow();
        txtNombre.setText((String) tableSushi.getValueAt(fila, 1));
    }//GEN-LAST:event_tableSushiMouseClicked

    private void cbIdSushiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdSushiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdSushiActionPerformed

    private void cbTipoSushiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoSushiActionPerformed
        if(cbTipoSushi.getSelectedIndex() > -1){
            String tipoSushi = (String)cbTipoSushi.getSelectedItem();
            llenarComboBoxSushi(tipoSushi);
        }else{
            cbTipoSushi.removeAll();
        }
    }//GEN-LAST:event_cbTipoSushiActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        menu menu = new menu();
        menu.setLocationRelativeTo(null);
        menu.setResizable(false);
        menu.setVisible(true);
        dispose();
        /*venta venta = new venta();
        venta.setLocationRelativeTo(null);
        venta.setResizable(false);
        venta.setVisible(false);
        dispose();*/
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbSushiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSushiActionPerformed
        if(cbSushi.getSelectedIndex() > -1){
            cbIdSushi.setSelectedIndex(cbSushi.getSelectedIndex());
        }else{
            cbSushi.removeAll();
        }
    }//GEN-LAST:event_cbSushiActionPerformed

    private void btnCerrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar1ActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String nombre, idsushi, preciosushi, tipo;
        int id_venta, id_sushi, id;

        nombre = (String)cbSushi.getSelectedItem();
        id_venta = Integer.parseInt(txtFolio.getText());
        idsushi = (String)cbIdSushi.getSelectedItem();
        id_sushi = Integer.parseInt(idsushi);
        id = Integer.parseInt(txtFolio.getText());
        tipo = (String)cbTipoSushi.getSelectedItem();
        

        try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO menu_sushi VALUES (?,?,?,?,?)");
            pst.setInt(2, id_venta);
            pst.setInt(3, id_sushi);
            pst.setString(4, tipo);
            pst.setString(5, nombre);
            pst.executeUpdate();

            llenarTableSushi(id_venta);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnCerrar1ActionPerformed

    private void btnCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar2ActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        int id = Integer.parseInt(txtFolio.getText());
        String nombre = txtNombre.getText();

        try
        {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea ELIMINAR este sushi?");

            if (confirmacion == 0){

                PreparedStatement pst = cn.prepareStatement("DELETE FROM menu_sushi WHERE ( nombre = ? AND id_menu = ? )");
                pst.setString(1, nombre);
                pst.setInt(2, id);
                pst.executeUpdate();

                limpiar();
                llenarTableSushi(id);
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnCerrar2ActionPerformed

    public void llenarTableSushi(int folio){
        
        DefaultTableModel stock = new DefaultTableModel();
        
        stock.addColumn("Tipo");
        stock.addColumn("Nombre");
        
        String [] fila = new String[5];

        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet sushi = st.executeQuery("SELECT * FROM menu_sushi WHERE id_menu =" + folio);
                        
            while(sushi.next()){
                
                fila[0] = sushi.getString(4);
                //fila[1] = stock.getString(3) + " " + stock.getString(4);
                fila[1] = sushi.getString(5);

                stock.addRow(fila);
            }
            
            tableSushi.setModel(stock);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }
    
    public void llenarComboBoxSushi(String tipo){
        
        cbSushi.removeAllItems();
        cbIdSushi.removeAllItems();
        DefaultComboBoxModel modeloSushi = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloId = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloPrecio = new DefaultComboBoxModel();
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            System.out.println(tipo);
            Statement st = cn.createStatement();
            ResultSet sushi = st.executeQuery("SELECT * FROM sushi WHERE tipo = '" + tipo + "'");
            
            while(sushi.next()){
                modeloSushi.addElement(sushi.getString(2));
                modeloId.addElement(sushi.getString(1));
                modeloPrecio.addElement(sushi.getString(4));
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
        cbSushi.setModel(modeloSushi);
        cbIdSushi.setModel(modeloId);
}
    
    public void limpiar(){
    txtNombre.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_sushi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_sushi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_sushi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_sushi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar1;
    private javax.swing.JButton btnCerrar2;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbIdSushi;
    private javax.swing.JComboBox<String> cbSushi;
    private javax.swing.JComboBox<String> cbTipoSushi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSushi;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
