
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raccoon
 */
public class plato_salsas extends javax.swing.JFrame {

    /**
     * Creates new form plato_salsas
     */
    public plato_salsas(String id) {
        initComponents();
        txtIdPlato.setText(id);
        llenarTableSalsa(Integer.parseInt(txtIdPlato.getText()));
        llenarComboBoxSalsa();
        
        cbIdSalsa.setVisible(false);
        txtIdPlato.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdPlato = new javax.swing.JTextField();
        cbSalsa = new javax.swing.JComboBox<>();
        cbIdSalsa = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSalsa = new javax.swing.JTable();
        btnAgregarIngredientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtIdPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPlatoActionPerformed(evt);
            }
        });

        cbSalsa.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSalsaActionPerformed(evt);
            }
        });

        cbIdSalsa.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbIdSalsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdSalsaActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Lucida Bright", 0, 10)); // NOI18N

        btnEliminar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnVolver.setText("<= Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tableSalsa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableSalsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ));
        tableSalsa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSalsaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSalsa);

        btnAgregarIngredientes.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnAgregarIngredientes.setText("Agregar");
        btnAgregarIngredientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarIngredientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVolver)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtIdPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbIdSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarIngredientes)
                    .addComponent(cbSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbIdSalsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPlatoActionPerformed

    private void cbSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSalsaActionPerformed
        if(cbSalsa.getSelectedIndex() > -1){
            cbIdSalsa.setSelectedIndex(cbSalsa.getSelectedIndex());
        }else{
            cbSalsa.removeAll();
        }
    }//GEN-LAST:event_cbSalsaActionPerformed

    private void cbIdSalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdSalsaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdSalsaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea ELIMINAR esta salsa?");

            if (confirmacion == 0){

                PreparedStatement pst = cn.prepareStatement("DELETE FROM palto_salsas WHERE id = ?");
                pst.setInt(1, Integer.parseInt(txtId.getText()));
                pst.executeUpdate();
                llenarTableSalsa(Integer.parseInt(txtIdPlato.getText()));
                limpiar();
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        plato_ingredientes plato_ingredientes = new plato_ingredientes(txtIdPlato.getText());
        plato_ingredientes.setLocationRelativeTo(null);
        plato_ingredientes.setResizable(true);
        plato_ingredientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void tableSalsaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSalsaMouseClicked
        int  fila = tableSalsa.getSelectedRow();
        txtId.setText((String) tableSalsa.getValueAt(fila, 0));
    }//GEN-LAST:event_tableSalsaMouseClicked

    private void btnAgregarIngredientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarIngredientesActionPerformed

        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String id = (String)cbIdSalsa.getSelectedItem();

        try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO plato_salsas VALUES (?,?,?,?)");
            pst.setInt(2, Integer.parseInt(txtIdPlato.getText()));
            pst.setInt(3, Integer.parseInt(id));
            pst.setString(4, (String)cbSalsa.getSelectedItem());
            pst.executeUpdate();
            limpiar();
            llenarTableSalsa(Integer.parseInt(txtIdPlato.getText()));
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarIngredientesActionPerformed

    public void llenarComboBoxSalsa(){
        
        cbSalsa.removeAllItems();
        cbIdSalsa.removeAllItems();
        DefaultComboBoxModel modeloSalsa = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloId = new DefaultComboBoxModel();
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet salsa = st.executeQuery("SELECT * FROM salsa");
            
            while(salsa.next()){
                modeloSalsa.addElement(salsa.getString(2));
                modeloId.addElement(salsa.getString(1));
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
        cbSalsa.setModel(modeloSalsa);
        cbIdSalsa.setModel(modeloId);
}
    
    public void llenarTableSalsa(int id){
        
        DefaultTableModel stock = new DefaultTableModel();
        
        stock.addColumn("id");
        stock.addColumn("Nombre");
        
        String [] fila = new String[4];

        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet plato = st.executeQuery("SELECT * FROM plato_salsas WHERE id_plato =" + id);
                        
            while(plato.next()){
                //System.out.println(stock.getString(2) + " " + stock.getString(3) + " " + stock.getString(4));
                fila[0] = plato.getString(1);
                //fila[1] = stock.getString(3) + " " + stock.getString(4);
                fila[1] = plato.getString(4);

                stock.addRow(fila);
            }
            
            tableSalsa.setModel(stock);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }
    
    public void limpiar(){
    txtId.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plato_salsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plato_salsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plato_salsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plato_salsas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarIngredientes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    public static javax.swing.JComboBox<String> cbIdSalsa;
    private javax.swing.JComboBox<String> cbSalsa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSalsa;
    private javax.swing.JTextField txtId;
    public static javax.swing.JTextField txtIdPlato;
    // End of variables declaration//GEN-END:variables
}
