
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raccoon
 */
public class venta_sashimi extends javax.swing.JFrame {

    /**
     * Creates new form venta_sashimi
     */
    public venta_sashimi(String folio) {
        initComponents();
        txtFolio.setText(folio);
        int sashimi = Integer.parseInt(txtFolio.getText());
        llenarTableSashimi(sashimi);
        String tipoSashimi = (String)cbTipoSashimi.getSelectedItem();
        llenarComboBoxSashimi(tipoSashimi);
        
        txtFolio.setVisible(false);
        cbIdSashimi.setVisible(false);
        cbSashimiPrecio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSashimi = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableSashimi = new javax.swing.JTable();
        cbIdSashimi = new javax.swing.JComboBox<>();
        cbSashimiPrecio = new javax.swing.JComboBox<>();
        cbTipoSashimi = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbSashimi.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbSashimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSashimiActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        txtFolio.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N

        tableSashimi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableSashimi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ));
        tableSashimi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSashimiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableSashimi);

        cbIdSashimi.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        cbIdSashimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdSashimiActionPerformed(evt);
            }
        });

        cbSashimiPrecio.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        cbSashimiPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSashimiPrecioActionPerformed(evt);
            }
        });

        cbTipoSashimi.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbTipoSashimi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sashimi", "Tiraritos" }));
        cbTipoSashimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoSashimiActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnVolver.setText("<=Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbTipoSashimi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbSashimi, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbIdSashimi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSashimiPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar)))
                    .addComponent(btnVolver))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoSashimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSashimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbIdSashimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbSashimiPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSashimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSashimiActionPerformed
        if(cbSashimi.getSelectedIndex() > -1){
            cbIdSashimi.setSelectedIndex(cbSashimi.getSelectedIndex());
            cbSashimiPrecio.setSelectedIndex(cbSashimi.getSelectedIndex());
        }else{
            cbSashimi.removeAll();
        }
    }//GEN-LAST:event_cbSashimiActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String nombre, idsashimi, preciosashimi;
        int id_venta, id_sashimi, precio, precio_final;

        nombre = (String)cbSashimi.getSelectedItem();
        id_venta = Integer.parseInt(txtFolio.getText());
        idsashimi = (String)cbIdSashimi.getSelectedItem();
        id_sashimi = Integer.parseInt(idsashimi);
        preciosashimi = (String)cbSashimiPrecio.getSelectedItem();
        precio = Integer.parseInt(preciosashimi);

        try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO venta_sashimi VALUES (?,?,?,?,?)");
            pst.setInt(2, id_venta);
            pst.setInt(3, id_sashimi);
            pst.setString(4, nombre);
            pst.setInt(5, precio);
            pst.executeUpdate();

            llenarTableSashimi(id_venta);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        int id, id_venta;

        id = Integer.parseInt(txtId.getText());
        id_venta = Integer.parseInt(txtFolio.getText());

        try
        {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea ELIMINAR?");

            if (confirmacion == 0){

                PreparedStatement pst = cn.prepareStatement("DELETE FROM venta_sashimi WHERE id = ?");
                pst.setInt(1, id);
                pst.executeUpdate();

                //limpiar();
                llenarTableSashimi(id_venta);
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tableSashimiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSashimiMouseClicked
        int  fila = tableSashimi.getSelectedRow();
        txtId.setText((String) tableSashimi.getValueAt(fila, 0));
    }//GEN-LAST:event_tableSashimiMouseClicked

    private void cbIdSashimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdSashimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdSashimiActionPerformed

    private void cbSashimiPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSashimiPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSashimiPrecioActionPerformed

    private void cbTipoSashimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoSashimiActionPerformed
        if(cbTipoSashimi.getSelectedIndex() > -1){
            String tipoSashimi = (String)cbTipoSashimi.getSelectedItem();         
            llenarComboBoxSashimi(tipoSashimi);
        }else{
            cbTipoSashimi.removeAll();
        }
    }//GEN-LAST:event_cbTipoSashimiActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        venta venta = new venta();
        venta.setLocationRelativeTo(null);
        venta.setResizable(false);
        venta.setVisible(true);
        dispose();
        /*venta venta = new venta();
        venta.setLocationRelativeTo(null);
        venta.setResizable(false);
        venta.setVisible(false);
        dispose();*/
    }//GEN-LAST:event_btnVolverActionPerformed

    public void llenarTableSashimi(int folio){
        
        DefaultTableModel stock = new DefaultTableModel();
        
        stock.addColumn("ID");
        stock.addColumn("Nombre");
        stock.addColumn("Precio");
        
        String [] fila = new String[5];

        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet sashimi = st.executeQuery("SELECT * FROM venta_sashimi WHERE id_venta =" + folio);
                        
            while(sashimi.next()){
                
                System.out.println(sashimi.getString(3));
                
                fila[0] = sashimi.getString(1);
                //fila[1] = stock.getString(3) + " " + stock.getString(4);
                fila[1] = sashimi.getString(4);
                fila[2] = sashimi.getString(5);

                stock.addRow(fila);
            }
            
            tableSashimi.setModel(stock);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }
    
    public void llenarComboBoxSashimi(String tipo){
        
        cbSashimi.removeAllItems();
        cbIdSashimi.removeAllItems();
        cbSashimiPrecio.removeAllItems();
        DefaultComboBoxModel modeloSashimi = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloId = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloPrecio = new DefaultComboBoxModel();
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            System.out.println(tipo);
            Statement st = cn.createStatement();
            ResultSet sashimi = st.executeQuery("SELECT * FROM sashimi WHERE tipo = '" + tipo + "'");
            
            while(sashimi.next()){
                modeloSashimi.addElement(sashimi.getString(2));
                modeloId.addElement(sashimi.getString(1));
                modeloPrecio.addElement(sashimi.getString(4));
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
        cbSashimiPrecio.setModel(modeloPrecio);
        cbSashimi.setModel(modeloSashimi);
        cbIdSashimi.setModel(modeloId);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venta_sashimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venta_sashimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venta_sashimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venta_sashimi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbIdSashimi;
    private javax.swing.JComboBox<String> cbSashimi;
    private javax.swing.JComboBox<String> cbSashimiPrecio;
    private javax.swing.JComboBox<String> cbTipoSashimi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableSashimi;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
