
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raccoon
 */
public class venta_acompañamiento extends javax.swing.JFrame {

    /**
     * Creates new form venta_acompañamiento
     */
    public venta_acompañamiento(String folio) {
        initComponents();
        txtFolio.setText(folio);
        int acompañamiento = Integer.parseInt(txtFolio.getText());
        llenarTableAcompañamiento(acompañamiento);
        llenarComboBoxAcompañamiento();
        
        txtFolio.setVisible(false);
        cbIdAcompañamiento.setVisible(false);
        cbAcompañamientoPrecio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        cbAcompañamiento = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAcompañamiento = new javax.swing.JTable();
        cbIdAcompañamiento = new javax.swing.JComboBox<>();
        cbAcompañamientoPrecio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnVolver.setText("<=Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        cbAcompañamiento.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbAcompañamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAcompañamientoActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        txtFolio.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N

        tableAcompañamiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableAcompañamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ));
        tableAcompañamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAcompañamientoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAcompañamiento);

        cbIdAcompañamiento.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        cbIdAcompañamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdAcompañamientoActionPerformed(evt);
            }
        });

        cbAcompañamientoPrecio.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        cbAcompañamientoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAcompañamientoPrecioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbAcompañamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbIdAcompañamiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId)
                            .addComponent(cbAcompañamientoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAcompañamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbIdAcompañamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbAcompañamientoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        venta venta = new venta();
        venta.setLocationRelativeTo(null);
        venta.setResizable(false);
        venta.setVisible(true);
        dispose();
        /*venta venta = new venta();
        venta.setLocationRelativeTo(null);
        venta.setResizable(false);
        venta.setVisible(false);
        dispose();*/
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbAcompañamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAcompañamientoActionPerformed
        if(cbAcompañamiento.getSelectedIndex() > -1){
            cbIdAcompañamiento.setSelectedIndex(cbAcompañamiento.getSelectedIndex());
            cbAcompañamientoPrecio.setSelectedIndex(cbAcompañamiento.getSelectedIndex());
        }else{
            cbAcompañamiento.removeAll();
        }
    }//GEN-LAST:event_cbAcompañamientoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String nombre, idacompañamiento, precioacompañamiento;
        int id_venta, id_acompañamiento, precio, precio_final;

        nombre = (String)cbAcompañamiento.getSelectedItem();
        id_venta = Integer.parseInt(txtFolio.getText());
        idacompañamiento= (String)cbIdAcompañamiento.getSelectedItem();
        id_acompañamiento = Integer.parseInt(idacompañamiento);
        precioacompañamiento = (String)cbAcompañamientoPrecio.getSelectedItem();
        precio = Integer.parseInt(precioacompañamiento);

        try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO venta_acompañamiento VALUES (?,?,?,?,?)");
            pst.setInt(2, id_venta);
            pst.setInt(3, id_acompañamiento);
            pst.setString(4, nombre);
            pst.setInt(5, precio);
            pst.executeUpdate();

            llenarTableAcompañamiento(id_venta);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        int id, id_venta;

        id = Integer.parseInt(txtId.getText());
        id_venta = Integer.parseInt(txtFolio.getText());

        try
        {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea ELIMINAR este acompañamiento?");

            if (confirmacion == 0){

                PreparedStatement pst = cn.prepareStatement("DELETE FROM venta_acompañamiento WHERE id = ?");
                pst.setInt(1, id);
                pst.executeUpdate();

                //limpiar();
                llenarTableAcompañamiento(id_venta);
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tableAcompañamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAcompañamientoMouseClicked
        int  fila = tableAcompañamiento.getSelectedRow();
        txtId.setText((String) tableAcompañamiento.getValueAt(fila, 0));
    }//GEN-LAST:event_tableAcompañamientoMouseClicked

    private void cbIdAcompañamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdAcompañamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdAcompañamientoActionPerformed

    private void cbAcompañamientoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAcompañamientoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAcompañamientoPrecioActionPerformed

    public void llenarTableAcompañamiento(int folio){
        
        DefaultTableModel stock = new DefaultTableModel();
        
        stock.addColumn("ID");
        stock.addColumn("Nombre");
        stock.addColumn("Precio");
        
        String [] fila = new String[5];

        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet acompañamiento = st.executeQuery("SELECT * FROM venta_acompañamiento WHERE id_venta =" + folio);
                        
            while(acompañamiento.next()){
                
                System.out.println(acompañamiento.getString(3));
                
                fila[0] = acompañamiento.getString(1);
                //fila[1] = stock.getString(3) + " " + stock.getString(4);
                fila[1] = acompañamiento.getString(4);
                fila[2] = acompañamiento.getString(5);

                stock.addRow(fila);
            }
            
            tableAcompañamiento.setModel(stock);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }
    
    public void llenarComboBoxAcompañamiento(){
        
        cbAcompañamiento.removeAllItems();
        cbIdAcompañamiento.removeAllItems();
        cbAcompañamientoPrecio.removeAllItems();
        DefaultComboBoxModel modeloAcompañamiento = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloId = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloPrecio = new DefaultComboBoxModel();
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet acompañamiento = st.executeQuery("SELECT * FROM acompañamiento");
            
            while(acompañamiento.next()){
                modeloAcompañamiento.addElement(acompañamiento.getString(2));
                modeloId.addElement(acompañamiento.getString(1));
                modeloPrecio.addElement(acompañamiento.getString(3));
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
        cbAcompañamiento.setModel(modeloAcompañamiento);
        cbIdAcompañamiento.setModel(modeloId);
        cbAcompañamientoPrecio.setModel(modeloPrecio);
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venta_acompañamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venta_acompañamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venta_acompañamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venta_acompañamiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbAcompañamiento;
    private javax.swing.JComboBox<String> cbAcompañamientoPrecio;
    private javax.swing.JComboBox<String> cbIdAcompañamiento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAcompañamiento;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
