
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Raccoon
 */
public class venta_plato extends javax.swing.JFrame {

    /**
     * Creates new form venta_plato
     */
    public venta_plato(String folio) {
        initComponents();
        txtFolio.setText(folio);
        int plato = Integer.parseInt(txtFolio.getText());
        llenarTablePlato(plato);
        String tipoPlato = (String)cbTipoPlato.getSelectedItem();
        llenarComboBoxPlato(tipoPlato);
        
        txtFolio.setVisible(false);
        cbIdPlato.setVisible(false);
        cbPlatoPrecio.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPlato = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtFolio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePlato = new javax.swing.JTable();
        cbIdPlato = new javax.swing.JComboBox<>();
        cbPlatoPrecio = new javax.swing.JComboBox<>();
        cbTipoPlato = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbPlato.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlatoActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N

        txtFolio.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N

        tablePlato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablePlato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Precio"
            }
        ));
        tablePlato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePlatoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePlato);

        cbIdPlato.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        cbIdPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIdPlatoActionPerformed(evt);
            }
        });

        cbPlatoPrecio.setFont(new java.awt.Font("Harlow Solid Italic", 0, 18)); // NOI18N
        cbPlatoPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlatoPrecioActionPerformed(evt);
            }
        });

        cbTipoPlato.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        cbTipoPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platos Frios", "Platos Calientes" }));
        cbTipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPlatoActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        btnVolver.setText("<=Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(cbTipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbIdPlato, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId)
                            .addComponent(cbPlatoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar)))
                    .addComponent(btnVolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnVolver)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbIdPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbPlatoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlatoActionPerformed
        if(cbPlato.getSelectedIndex() > -1){
            cbIdPlato.setSelectedIndex(cbPlato.getSelectedIndex());
            cbPlatoPrecio.setSelectedIndex(cbPlato.getSelectedIndex());
        }else{
            cbPlato.removeAll();
        }
    }//GEN-LAST:event_cbPlatoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String nombre, idplato, precioplato;
        int id_venta, id_plato, precio, precio_final;

        nombre = (String)cbPlato.getSelectedItem();
        id_venta = Integer.parseInt(txtFolio.getText());
        idplato = (String)cbIdPlato.getSelectedItem();
        id_plato = Integer.parseInt(idplato);
        precioplato = (String)cbPlatoPrecio.getSelectedItem();
        precio = Integer.parseInt(precioplato);

        try
        {
            PreparedStatement pst = cn.prepareStatement("INSERT INTO venta_plato VALUES (?,?,?,?,?)");
            pst.setInt(2, id_venta);
            pst.setInt(3, id_plato);
            pst.setString(4, nombre);
            pst.setInt(5, precio);
            pst.executeUpdate();

            llenarTablePlato(id_venta);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        int id, id_venta;

        id = Integer.parseInt(txtId.getText());
        id_venta = Integer.parseInt(txtFolio.getText());

        try
        {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea ELIMINAR este plato?");

            if (confirmacion == 0){

                PreparedStatement pst = cn.prepareStatement("DELETE FROM venta_plato WHERE id = ?");
                pst.setInt(1, id);
                pst.executeUpdate();

                //limpiar();
                llenarTablePlato(id_venta);
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablePlatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePlatoMouseClicked
        int  fila = tablePlato.getSelectedRow();
        txtId.setText((String) tablePlato.getValueAt(fila, 0));
    }//GEN-LAST:event_tablePlatoMouseClicked

    private void cbIdPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIdPlatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIdPlatoActionPerformed

    private void cbPlatoPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlatoPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPlatoPrecioActionPerformed

    private void cbTipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPlatoActionPerformed
        if(cbTipoPlato.getSelectedIndex() > -1){
            String tipoPlato = (String)cbTipoPlato.getSelectedItem();
            llenarComboBoxPlato(tipoPlato);
        }else{
            cbTipoPlato.removeAll();
        }
    }//GEN-LAST:event_cbTipoPlatoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        venta venta = new venta();
        venta.setLocationRelativeTo(null);
        venta.setResizable(false);
        venta.setVisible(true);
        dispose();
        /*venta venta = new venta();
        venta.setLocationRelativeTo(null);
        venta.setResizable(false);
        venta.setVisible(false);
        dispose();*/
    }//GEN-LAST:event_btnVolverActionPerformed

    public void llenarTablePlato(int folio){
        
        DefaultTableModel stock = new DefaultTableModel();
        
        stock.addColumn("ID");
        stock.addColumn("Nombre");
        stock.addColumn("Precio");
        
        String [] fila = new String[5];

        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            Statement st = cn.createStatement();
            ResultSet sushi = st.executeQuery("SELECT * FROM venta_plato WHERE id_venta =" + folio);
                        
            while(sushi.next()){
                
                System.out.println(sushi.getString(3));
                
                fila[0] = sushi.getString(1);
                //fila[1] = stock.getString(3) + " " + stock.getString(4);
                fila[1] = sushi.getString(4);
                fila[2] = sushi.getString(5);

                stock.addRow(fila);
            }
            
            tablePlato.setModel(stock);
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
    }
    
    public void llenarComboBoxPlato(String tipo){
        
        cbPlato.removeAllItems();
        cbIdPlato.removeAllItems();
        cbPlatoPrecio.removeAllItems();
        DefaultComboBoxModel modeloPlato = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloId = new DefaultComboBoxModel();
        DefaultComboBoxModel modeloPrecio = new DefaultComboBoxModel();
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        
        try
        {
            System.out.println(tipo);
            Statement st = cn.createStatement();
            ResultSet plato = st.executeQuery("SELECT * FROM plato WHERE tipo = '" + tipo + "'");
            
            while(plato.next()){
                modeloPlato.addElement(plato.getString(2));
                modeloId.addElement(plato.getString(1));
                modeloPrecio.addElement(plato.getString(4));
            }
        }
        catch (SQLException ex)
        {
            System.out.print(ex.getMessage());
        }
        cbPlatoPrecio.setModel(modeloPrecio);
        cbPlato.setModel(modeloPlato);
        cbIdPlato.setModel(modeloId);
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(venta_plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(venta_plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(venta_plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(venta_plato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbIdPlato;
    private javax.swing.JComboBox<String> cbPlato;
    private javax.swing.JComboBox<String> cbPlatoPrecio;
    private javax.swing.JComboBox<String> cbTipoPlato;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePlato;
    private javax.swing.JTextField txtFolio;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
